# Generated by Django 4.2.26 on 2025-11-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='name',
            field=models.CharField(default='Placeholder', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
